server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akash149/microservice-config
          clone-on-start: true

# eureka:
#   instance:
#     prefer-ip-address: true

#   client:
#     register-With-Eureka: true
#     fetch-Registry: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka
